services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: para_shop_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
